# Generated by Django 2.0.2 on 2018-02-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180224_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='products', to='products.Category'),
        ),
    ]
